version: '3.8'

services:
  nasal-online:
    image: sidi762/nasal-online
    container_name: nasal-online
    restart: unless-stopped
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "1"
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    pids_limit: 100
